ci: Check Git repository status to avoid omitting Cargo.lock updates
To avoid contributors forgetting to commit the Cargo.lock updates, let's
add a step to the sterile.yml workflow, to check whether building or
testing the changes resulted in an updated Cargo.lock file. To do that,
we check the result value from "git diff --quiet".

Signed-off-by: Quentin Monnet <qmo@qmon.net>

diff --git a/.github/workflows/sterile.yml b/.github/workflows/sterile.yml
--- a/.github/workflows/sterile.yml
+++ b/.github/workflows/sterile.yml
@@ -107,6 +107,14 @@ jobs:
           just debug_justfile="${{inputs.debug_justfile}}" rust="${{matrix.rust}}" profile=dev target=x86_64-unknown-linux-gnu \
             sterile cargo clippy --all-targets --all-features -- -D warnings
 
+      - name: "check Git status"
+        run: |
+          if ! git diff --quiet; then
+              printf '::error::Git working directory is dirty, missing Cargo.lock update?\n\n'
+              git --no-pager diff
+              printf '\nPlease commit the changes and update your Pull Request\n'
+              exit 1
+          fi
 
       - name: "Setup tmate session for debug"
         if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
